<?php
/**
 * Created by PhpStorm.
 * User: soft
 * Date: 2019-01-25
 * Time: 11:17
 */

namespace api\controllers;


use common\models\Article;
use Yii;
use yii\data\ActiveDataProvider;
use yii\filters\auth\QueryParamAuth;
use yii\helpers\ArrayHelper;
use yii\rest\ActiveController;

class ArticleController extends ActiveController
{
    public $modelClass = "common\models\Article";

    public function actions()
    {
        $actions = parent::actions();
        unset($actions['index']);
        return $actions; // TODO: Change the autogenerated stub
    }

    public function behaviors()
    {
        return ArrayHelper::merge(parent::behaviors(), [
            'authenticatior' => [
                'class' => QueryParamAuth::className()
            ]
        ]);
    }


    public function actionIndex(){
        $request = Yii::$app->request->queryParams;
        $modelClass = $this->modelClass;
        return new ActiveDataProvider([
            'query' => $modelClass::find()->asArray(),
             'pagination' => ['pageSize' => 5,
                 'page' => $request['page']],
        ]);
    }


    public function actionSearch(){
        return Article::find()->where(['like','title',$_POST['keyword']])->all();
    }

}